import { useCallback, useEffect, useState } from 'react'
import { Link } from '@tanstack/react-router'
import ReactMarkdown from 'react-markdown'
import { ArrowUpRight, Play, RefreshCw, Search } from 'lucide-react'
import { Button } from './ui'
type Kind='scout'|'assessment'|'lp'
type Run={id:string;kind:Kind;status:string;request:string;result:string|null;created_at:string;error_code:string|null}
type Data={runs:Run[];readiness:Record<Kind,{ready:boolean;reason:string;source?:string}>;lp:{records:{id:string;name:string;company:string;status:string;owner:string;investorType:string}[];source?:string;latestSourceChange:string|null}}
export function AgentRunsPage({kind,title}:{kind:Kind;title:string}){
  const[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[request,setRequest]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string|null>(null),[query,setQuery]=useState('')
  const refresh=useCallback(async()=>{try{const r=await fetch('/api/agent-runs'),v=await r.json();if(!r.ok)throw Error(v.error||'Runs are unavailable.');setData(v);setError('')}catch(e){setError(e instanceof Error?e.message:'Runs are unavailable.')}},[])
  useEffect(()=>{void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},10_000);return()=>clearInterval(timer)},[refresh])
  const start=async()=>{setBusy(true);setError('');try{const r=await fetch('/api/agent-runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,request})}),v=await r.json();if(!r.ok)throw Error(v.error);setSelected(v.id);await refresh()}catch(e){setError(e instanceof Error?e.message:'The run failed.');await refresh()}finally{setBusy(false)}}
  const runs=data?.runs.filter(r=>r.kind===kind)||[],active=runs.find(r=>r.id===selected),ready=data?.readiness[kind]
  return <div className="page runs-page"><header className="page-header"><h1>{title}</h1><Button onClick={()=>void refresh()}><RefreshCw/>Refresh</Button></header>
    <div className="runs-links">{kind==='scout'&&<Link to="/companies" className="button">Companies and documents<ArrowUpRight/></Link>}{ready?.source&&<a className="button" href={ready.source} target="_blank" rel="noopener noreferrer">Claude source project<ArrowUpRight/></a>}</div>
    {error&&<p className="form-error" role="alert">{error}</p>}
    <section className="integration-section"><h2 className="section-caption">New run</h2><div className="settings-panel surface"><label className="settings-field"><span>{kind==='assessment'?'Company and assessment request':'Research focus'}</span><textarea rows={3} maxLength={4000} value={request} onChange={e=>setRequest(e.target.value)} placeholder={kind==='assessment'?'Assess a company using its founder email and pitch deck…':'Sector, geography, and stage…'}/></label>{ready&&<p className="muted small">{ready.reason}</p>}<div className="dialog-actions"><Button className="primary" disabled={busy||!ready?.ready||!request.trim()} onClick={()=>void start()}><Play/>{busy?'Running…':'Start run'}</Button></div></div></section>
    <section className="integration-section"><h2 className="section-caption">Run history</h2><div className="surface run-list">{!runs.length?<p className="muted empty-state">No runs yet.</p>:runs.map(run=><button key={run.id} className="run-row" aria-pressed={selected===run.id} onClick={()=>setSelected(run.id)}><span><strong>{run.request}</strong><small>{new Date(run.created_at).toLocaleString()}</small></span><span>{run.status==='complete'?'Complete':run.status==='running'?'Running':'Needs attention'}</span></button>)}</div>{active&&<article className="surface run-result"><h2>{active.request}</h2>{active.result?<ReactMarkdown disallowedElements={['img','iframe','script']} components={{a:({children,href})=><a href={href} target="_blank" rel="noopener noreferrer">{children}</a>}}>{active.result}</ReactMarkdown>:<p className="muted">{active.status==='running'?'Research is in progress. This history updates automatically.':'This run did not finish. Check the source connections before retrying.'}</p>}</article>}</section>
    {kind==='lp'&&data?.lp&&<section className="integration-section"><h2 className="section-caption">LP pipeline</h2><p className="muted small">Claude project snapshot{data.lp.latestSourceChange?` · Latest source change ${new Date(data.lp.latestSourceChange).toLocaleDateString()}`:''} · {data.lp.records.length} entries</p><label className="search-field"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search LPs" aria-label="Search LPs"/></label><div className="data-table-scroll surface"><table className="workspace-table"><thead><tr><th>Name</th><th>Company</th><th>Stage</th><th>Owner</th></tr></thead><tbody>{data.lp.records.filter(r=>`${r.name} ${r.company}`.toLowerCase().includes(query.toLowerCase())).map(r=><tr key={r.id}><td>{r.name}</td><td>{r.company||'—'}</td><td>{r.status||'—'}</td><td>{r.owner||'—'}</td></tr>)}</tbody></table></div></section>}
  </div>
}
