import { useCallback, useEffect, useState } from 'react'
import { Download, RefreshCw, Search } from 'lucide-react'
import { Button } from './ui'
type Data={companies:{id:string;name:string;source:string;notion_status:string;document_count:number}[];documents:{id:string;name:string;company_id:string}[];ingestions:{id:string;status:string;reason:string;created_at:string}[];notionConfigured:boolean}
export function CompaniesPage(){
  const[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[busy,setBusy]=useState('')
  const refresh=useCallback(async()=>{try{const r=await fetch('/api/companies'),v=await r.json();if(!r.ok)throw Error(v.error||'Companies are unavailable.');setData(v);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load companies.')}},[])
  useEffect(()=>{void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},10_000);return()=>clearInterval(timer)},[refresh])
  const sync=async(companyId:string)=>{setBusy(companyId);setError('');try{const r=await fetch('/api/companies',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'sync-notion',companyId})}),v=await r.json();if(!r.ok||v.status!=='synced')throw Error(v.status==='needs_setup'?'Notion is awaiting setup.':'Notion sync needs attention.');await refresh()}catch(e){setError(e instanceof Error?e.message:'Sync failed.')}finally{setBusy('')}}
  return <div className="page"><header className="page-header"><h1>Companies and documents</h1><Button onClick={()=>void refresh()}><RefreshCw/>Refresh</Button></header>{error&&<p className="form-error" role="alert">{error}</p>}<label className="search-field"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search companies" aria-label="Search companies"/></label><div className="integration-section">{data?.companies.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())).map(company=><article className="surface company-source" key={company.id}><div className="setting-access-row"><span><strong>{company.name}</strong><small>{company.source==='airtable'?'Airtable portfolio':'Founder correspondence'} · {company.document_count} documents</small></span>{data.notionConfigured?<Button disabled={!!busy} onClick={()=>void sync(company.id)}>{company.notion_status==='synced'?'Sync Notion':'Add to Notion'}</Button>:<span className="muted small">Notion awaiting setup</span>}</div>{data.documents.filter(d=>d.company_id===company.id).map(doc=><a className="document-row" key={doc.id} href={`/api/documents/${doc.id}`}><Download size={15}/>{doc.name}</a>)}</article>)}</div><section className="integration-section"><h2 className="section-caption">Email processing</h2><div className="surface run-list">{data?.ingestions.length?data.ingestions.map(item=><div className="run-row" key={item.id}><span><strong>{item.status==='indexed'?'Added to Brain':item.status==='excluded'?'Excluded':item.status==='review'?'Held for review':item.status==='indexing'?'Indexing':'Needs attention'}</strong><small>{item.reason}</small></span><small>{new Date(item.created_at).toLocaleString()}</small></div>):<p className="empty-state muted">No emails have passed through the screened pipeline yet.</p>}</div></section></div>
}
