import { Link } from '@tanstack/react-router'
import { ArrowUpRight, Check, Plus, RefreshCw, Search } from 'lucide-react'
import { useState } from 'react'
import { integrationAction, useIntegrationOverview } from '../lib/integrations-client'
import { SourceLogo } from './source-logo'
import { Button, Modal } from './ui'
import { MailboxConnection } from './mailbox-connection'

type Resource={id:string;title:string;url:string;object:string}
export function ConnectorsPage() {
  const {data,error,loading,refresh}=useIntegrationOverview()
  const [query,setQuery]=useState(''),[dialog,setDialog]=useState<'choose'|'gmail'|'notion'|null>(null),[token,setToken]=useState('')
  const [resources,setResources]=useState<Resource[]>([]),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[actionError,setActionError]=useState(''),[notice,setNotice]=useState('')
  const restoreFocus=()=>{if(!document.querySelector('[role=dialog]'))document.querySelector<HTMLButtonElement>('[aria-label="Connect app"]')?.focus()}
  const close=()=>{setDialog(null);setToken('');setActionError('')}
  const act=async(work:()=>Promise<void>)=>{setBusy(true);setActionError('');try{await work()}catch(error){setActionError(error instanceof Error?error.message:'Please try again.')}finally{setBusy(false)}}
  const notion=()=>{setNotice('');setDialog('notion');setResources([]);setSelected([]);setActionError('');if(data?.capabilities.notion)void act(async()=>{const result=await integrationAction<{resources:Resource[];selected:string[]}>('notion-resources');setResources(result.resources);setSelected(result.selected)})}
  const visible=data?.connections.filter(c=>`${c.name} ${c.provider} ${c.account||''}`.toLowerCase().includes(query.toLowerCase()))||[]
  return <div className="page integrations-page"><header className="page-header"><h1>Connected Sources</h1><Button aria-label="Connect app" onClick={()=>{setDialog('choose');setActionError('')}}><Plus/>Connect app</Button></header>
    <div className="integration-toolbar"><label className="search-field"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search connected apps" aria-label="Search connected apps"/></label><Button onClick={()=>void refresh()} disabled={loading}><RefreshCw/>Refresh</Button><Link to="/settings" className="button">Settings<ArrowUpRight/></Link></div>
    {error && <div className="response-error" role="alert"><p>{error}</p><Button onClick={()=>void refresh()}>Try again</Button></div>}
    {notice && <p className="save-notice" role="status">{notice}</p>}
    {!data && loading?<p className="muted" role="status">Checking connections…</p>:<div className="connector-grid">{visible.map(connection=><article key={connection.id} className="connector-card surface"><div className="connector-brand"><SourceLogo provider={connection.provider}/></div><div className="connector-copy"><h2>{connection.name}</h2><p>{connection.account||'Choose the pages you want to share'}</p><div className="connector-status"><span data-status={connection.status}>{connection.status==='connected'?'Connected':connection.status==='pending'?'Setup in progress':connection.status==='error'?'Needs attention':'Not connected'}</span><span>{connection.method}</span></div>{connection.lastSync && <small>Synced {new Date(connection.lastSync).toLocaleString()}</small>}{connection.documentCount!==undefined && <small>{connection.documentCount} {connection.provider==='airtable'?(connection.documentCount===1?'company':'companies'):(connection.documentCount===1?'document':'documents')}</small>}{connection.error && <p className="field-error">{connection.error}</p>}</div>{connection.provider==='notion' && <Button className="ghost" onClick={notion}>{connection.status==='disconnected'?'Connect':'Choose pages'}<ArrowUpRight/></Button>}</article>)}</div>}
    {data && !visible.length && <div className="empty-state"><p>No matching connections.</p><Button className="ghost" onClick={()=>setQuery('')}>Clear search</Button></div>}
    <MailboxConnection/><section className="integration-section"><h2 className="section-caption">Add a source</h2><div className="available-connectors"><button onClick={()=>{setDialog('gmail');setActionError('')}}><SourceLogo provider="Gmail"/><span><strong>Gmail</strong><small>Connect a team mailbox</small></span><Plus/></button><button onClick={notion}><SourceLogo provider="Notion"/><span><strong>Notion</strong><small>Choose pages and databases</small></span><Plus/></button></div></section>
    <Modal restoreFocus={restoreFocus} open={dialog==='choose'} onOpenChange={open=>{if(!open)close()}} title="Connect an app"><div className="available-connectors"><button onClick={()=>setDialog('gmail')}><SourceLogo provider="Gmail"/><span><strong>Gmail</strong><small>Connect a team mailbox</small></span><ArrowUpRight/></button><button onClick={notion}><SourceLogo provider="Notion"/><span><strong>Notion</strong><small>Choose pages and databases</small></span><ArrowUpRight/></button></div></Modal><Modal restoreFocus={restoreFocus} open={dialog==='gmail'} onOpenChange={open=>{if(!open)close()}} title="Connect Gmail"><p className="muted">Email knowledge from team mailboxes is available to admins only.</p><MailboxConnection/><div className="dialog-actions"><Button onClick={close}>Done</Button></div></Modal>
    <Modal restoreFocus={restoreFocus} open={dialog==='notion'} onOpenChange={open=>{if(!open)close()}} title="Connect Notion"><p className="muted">Use a workspace integration with Read, Insert, and Update content access to the deal-flow database. This lets approved founder emails create companies and attach their decks.</p>{!data?.capabilities.notion && !resources.length && <><label className="settings-field"><span>Integration secret</span><input type="password" value={token} onChange={e=>setToken(e.target.value)} autoComplete="new-password" placeholder="ntn_…"/></label><Button disabled={busy||!token.trim()} onClick={()=>void act(async()=>{const result=await integrationAction<{resources:Resource[]}>('connect-notion',{token});setToken('');setResources(result.resources);await refresh()})}>{busy?'Verifying…':'Verify connection'}</Button></>}
      {(data?.capabilities.notion||resources.length>0) && <div className="notion-resource-list"><h3>Pages to include</h3><p className="muted small">Selected pages include their child pages and databases.</p>{resources.map(resource=><label className="resource-choice" key={resource.id}><input type="checkbox" checked={selected.includes(resource.id)} onChange={e=>setSelected(previous=>e.target.checked?[...previous,resource.id]:previous.filter(id=>id!==resource.id))}/><span><strong>{resource.title}</strong><small>{resource.object.replace('_',' ')}</small></span><Check/></label>)}{!resources.length && !busy && <p className="connection-help">No shared pages are available. Ask the workspace owner to share the relevant pages with the integration, then retry.</p>}</div>}
      {actionError && <p className="form-error" role="alert">{actionError}</p>}<div className="dialog-actions"><Button onClick={close}>Cancel</Button><Button className="primary" disabled={busy||!selected.length} onClick={()=>void act(async()=>{const result=await integrationAction<{documentCount:number}>('sync-notion',{ids:selected});close();setNotice(`${result.documentCount} Notion documents are ready in the Brain.`);await refresh()})}>{busy?'Syncing…':'Sync selected pages'}</Button></div>
    </Modal>
  </div>
}
