import { useEffect, useState } from 'react'
import { ArrowUpRight, Check, RefreshCw, ShieldCheck } from 'lucide-react'
import type { IntegrationSettings, ScreeningResult } from '../lib/integration-types'
import { integrationAction, useIntegrationOverview } from '../lib/integrations-client'
import { Button, Picker } from './ui'

const examples = {
  'Founder update': { from:'founder@company.example',subject:'September operating update',body:'Revenue grew 18% this quarter. We have 16 months of runway and plan to hire two engineers next year. Can you introduce us to an industrial pilot customer?' },
  'Personnel message': { from:'people@fund.example',subject:'Confidential personnel review',body:'Attached is an individual employee performance review. This thread also discusses their compensation and benefits.' },
  'Mixed thread': { from:'founder@company.example',subject:'Operating update and forwarded discussion',body:'We signed three customer pilots.\n\nForwarded thread: People operations\nPlease review an individual employee grievance and their salary adjustment.' },
}
export function SettingsPage() {
  const {data,setData,error,loading,refresh}=useIntegrationOverview(),[draft,setDraft]=useState<IntegrationSettings|null>(null)
  const [busy,setBusy]=useState(''),[message,setMessage]=useState(''),[saveError,setSaveError]=useState(''),[screenError,setScreenError]=useState('')
  const [example,setExample]=useState('Founder update'),[sample,setSample]=useState(examples['Founder update']),[result,setResult]=useState<ScreeningResult|null>(null)
  useEffect(()=>{if(data && !draft)setDraft(structuredClone(data.settings))},[data,draft])
  const run=async(name:string,work:()=>Promise<void>)=>{setBusy(name);setMessage('');setSaveError('');try{await work()}catch(error){setSaveError(error instanceof Error?error.message:'Please try again.')}finally{setBusy('')}}
  const update=(apply:(settings:IntegrationSettings)=>IntegrationSettings)=>{setDraft(previous=>previous?apply(previous):previous);setMessage('')}
  return <div className="page settings-page"><header className="page-header"><h1>Settings</h1><Button className="primary" disabled={!draft||!!busy} onClick={()=>void run('save',async()=>{const saved=await integrationAction<{settings:IntegrationSettings}>('save-settings',{settings:draft});setDraft(saved.settings);setData(previous=>previous?{...previous,settings:saved.settings}:previous);setMessage('Settings saved.')})}>{busy==='save'?'Saving…':'Save changes'}</Button></header>
    {error && <div className="response-error" role="alert"><p>{error}</p><Button onClick={()=>void refresh()}>Try again</Button></div>}{saveError && <p className="form-error" role="alert">{saveError}</p>}{message && <p className="save-notice" role="status"><Check/>{message}</p>}
    {!draft && loading?<p className="muted" role="status">Loading settings…</p>:draft && <>
    <section className="settings-section"><div className="settings-section-heading"><h2>Investment thesis</h2><p>Fund context used for company assessments and investment questions.</p></div><div className="settings-panel surface"><label className="settings-field"><span>Thesis</span><textarea rows={10} value={draft.thesis.text} onChange={e=>update(s=>({...s,thesis:{...s.thesis,text:e.target.value}}))}/></label><div className="settings-source">{draft.thesis.sourceUrl && <a href={draft.thesis.sourceUrl} target="_blank" rel="noopener noreferrer">Source reference<ArrowUpRight/></a>}<Button className="ghost" disabled={!!busy} onClick={()=>void run('thesis',async()=>{const result=await integrationAction<{thesis:{text:string;sourceUrl:string}}>('refresh-thesis');setDraft(previous=>previous?{...previous,thesis:{...previous.thesis,...result.thesis,assessment:previous.thesis.assessment}}:previous);setMessage('Thesis refreshed from Airtable. Assessment guidance is preserved.')})}><RefreshCw/>Refresh from Airtable</Button></div><label className="settings-field"><span>Assessment guidance</span><small>Paste the approved Claude project instructions to guide startup assessments.</small><textarea rows={7} value={draft.thesis.assessment} onChange={e=>update(s=>({...s,thesis:{...s.thesis,assessment:e.target.value}}))} placeholder="Impact, team, technology, policy, venture case, and the evidence required for each…"/></label></div></section>
    <section className="settings-section"><div className="settings-section-heading"><h2>Knowledge access</h2><p>Choose which sources scouts can use.</p></div><div className="settings-panel surface">{([{label:'Portfolio records',description:'Company records and reported financial figures from Airtable.',checked:draft.portfolioScoutAccess,change:(checked:boolean)=>update(s=>({...s,portfolioScoutAccess:checked}))},{label:'Investment thesis',description:'The fund thesis and assessment guidance.',checked:draft.thesis.scoutAccess,change:(checked:boolean)=>update(s=>({...s,thesis:{...s.thesis,scoutAccess:checked}}))},{label:'Selected Notion pages',description:'Only the pages shared through Connected Sources.',checked:draft.notionScoutAccess,change:(checked:boolean)=>update(s=>({...s,notionScoutAccess:checked}))}]).map(item=><label className="setting-access-row" key={item.label}><span><strong>{item.label}</strong><small>{item.description}</small></span><input className="quiet-switch" type="checkbox" checked={item.checked} onChange={e=>item.change(e.target.checked)} aria-label={`Share ${item.label.toLowerCase()} with scouts`}/></label>)}<div className="setting-access-row"><span><strong>Email and LP relationships</strong><small>Available to admins only.</small></span><ShieldCheck/></div></div></section>
    <section className="settings-section"><div className="settings-section-heading"><h2>Email screening</h2><p>Review the proposed policy before changing live email ingestion.</p><span className="screening-mode">Enforcement off</span></div><div className="settings-panel surface"><p className="muted small">Messages below are classified for review only. Your inbox and live ingestion flow are unchanged.</p><div className="settings-field-pair"><label className="settings-field"><span>Excluded senders</span><textarea rows={3} value={draft.screening.blockedSenders.join('\n')} onChange={e=>update(s=>({...s,screening:{...s.screening,blockedSenders:e.target.value.split('\n')}}))} placeholder="One email address per line"/></label><label className="settings-field"><span>Excluded Gmail labels</span><textarea rows={3} value={draft.screening.blockedLabels.join('\n')} onChange={e=>update(s=>({...s,screening:{...s.screening,blockedLabels:e.target.value.split('\n')}}))}/></label></div><div className="screening-form"><div className="screening-form-heading"><h3>Screen a message</h3><Picker label="Screening example" value={example} options={Object.keys(examples)} onChange={value=>{setExample(value);setSample(examples[value as keyof typeof examples]);setResult(null);setScreenError('')}}/></div><div className="settings-field-pair"><label className="settings-field"><span>Sender</span><input value={sample.from} onChange={e=>{setSample(s=>({...s,from:e.target.value}));setResult(null)}}/></label><label className="settings-field"><span>Subject</span><input value={sample.subject} onChange={e=>{setSample(s=>({...s,subject:e.target.value}));setResult(null)}}/></label></div><label className="settings-field"><span>Message</span><textarea rows={6} value={sample.body} onChange={e=>{setSample(s=>({...s,body:e.target.value}));setResult(null)}}/></label><Button disabled={!!busy||!sample.body.trim()} onClick={()=>{setBusy('screen');setScreenError('');setResult(null);void integrationAction<{result:ScreeningResult;enforced:false}>('screen-email',{email:sample,policy:draft.screening}).then(data=>setResult(data.result)).catch(error=>setScreenError(error.message)).finally(()=>setBusy(''))}}>{busy==='screen'?'Screening…':'Screen message'}</Button>{screenError && <p className="form-error" role="alert">{screenError}</p>}{result && <div className="screening-result" role="status" data-decision={result.decision}><strong>{result.decision==='include'?'Include in knowledge':result.decision==='exclude'?'Exclude from knowledge':'Needs review'}</strong><p>{result.reason}</p><small>{result.method==='model'?'Luna':result.method==='rules'?'Policy rule':'Held for review'} · No ingestion action taken</small></div>}</div></div></section>
    </>}
  </div>
}
